// Generated by tmpl
// https://github.com/benbjohnson/tmpl
//
// DO NOT EDIT!
// Source: arraybuilder_numeric.gen.go.tmpl

package arrow

import (
	"github.com/influxdata/arrow/memory"
)

type Int32ArrayBuilder struct {
	arrayBuilder

	data    *memory.PoolBuffer
	rawData []int32
}

func NewInt32ArrayBuilder(pool memory.Allocator) *Int32ArrayBuilder {
	return &Int32ArrayBuilder{arrayBuilder: arrayBuilder{pool: pool}}
}

//region: append

func (b *Int32ArrayBuilder) Append(v int32) {
	b.Reserve(1)
	b.UnsafeAppend(v)
}

func (b *Int32ArrayBuilder) AppendNull() {
	b.Reserve(1)
	b.UnsafeAppendBoolToBitmap(false)
}

func (b *Int32ArrayBuilder) UnsafeAppend(v int32) {
	setBit(b.nullBitmap.Bytes(), b.length)
	b.rawData[b.length] = v
	b.length++
}

func (b *Int32ArrayBuilder) UnsafeAppendBoolToBitmap(isValid bool) {
	if isValid {
		setBit(b.nullBitmap.Bytes(), b.length)
	} else {
		b.nullN++
	}
	b.length++
}

// AppendValues will append the values in the v slice. The valid slice determines which values
// in v are valid (not null). The valid slice must either be empty or be equal in length to v. If empty,
// all values in v are appended and considered valid.
func (b *Int32ArrayBuilder) AppendValues(v []int32, valid []bool) {
	if len(v) != len(valid) && len(valid) != 0 {
		panic("len(v) != len(valid) && len(valid) != 0")
	}

	b.Reserve(len(v))
	if len(v) > 0 {
		Int32Traits{}.Copy(b.rawData[b.length:], v)
	}
	b.arrayBuilder.unsafeAppendBoolsToBitmap(valid, len(v))
}

//endregion

func (b *Int32ArrayBuilder) Init(capacity int) {
	b.arrayBuilder.init(capacity)

	b.data = memory.NewPoolBuffer(b.pool)
	bytesN := Int32Traits{}.BytesRequired(capacity)
	b.data.Resize(bytesN)
	b.rawData = Int32Traits{}.CastFromBytes(b.data.Bytes())
}

// Reserve ensures there is enough space for adding the specified number of elements
// by checking the capacity and calling Resize if necessary.
func (b *Int32ArrayBuilder) Reserve(elements int) {
	b.arrayBuilder.reserve(elements, b.Resize)
}

func (b *Int32ArrayBuilder) Resize(capacity int) {
	if capacity < minBuilderCapacity {
		capacity = minBuilderCapacity
	}

	if b.capacity == 0 {
		b.Init(capacity)
	} else {
		b.arrayBuilder.resize(capacity, b.Init)
		b.data.Resize(Int32Traits{}.BytesRequired(capacity))
		b.rawData = Int32Traits{}.CastFromBytes(b.data.Bytes())
	}
}

func (b *Int32ArrayBuilder) Finish() *Int32Array {
	data := b.finishInternal()
	return NewInt32Array(data)
}

func (b *Int32ArrayBuilder) finishInternal() *ArrayData {
	bytesRequired := Int32Traits{}.BytesRequired(b.length)
	if bytesRequired > 0 && bytesRequired < b.data.Len() {
		// trim buffers
		b.data.Resize(bytesRequired)
	}
	res := NewArrayData(PrimitiveTypes.Int32, b.length, []*memory.Buffer{&b.nullBitmap.Buffer, &b.data.Buffer}, b.nullN)
	b.reset()

	return res
}

type Int64ArrayBuilder struct {
	arrayBuilder

	data    *memory.PoolBuffer
	rawData []int64
}

func NewInt64ArrayBuilder(pool memory.Allocator) *Int64ArrayBuilder {
	return &Int64ArrayBuilder{arrayBuilder: arrayBuilder{pool: pool}}
}

//region: append

func (b *Int64ArrayBuilder) Append(v int64) {
	b.Reserve(1)
	b.UnsafeAppend(v)
}

func (b *Int64ArrayBuilder) AppendNull() {
	b.Reserve(1)
	b.UnsafeAppendBoolToBitmap(false)
}

func (b *Int64ArrayBuilder) UnsafeAppend(v int64) {
	setBit(b.nullBitmap.Bytes(), b.length)
	b.rawData[b.length] = v
	b.length++
}

func (b *Int64ArrayBuilder) UnsafeAppendBoolToBitmap(isValid bool) {
	if isValid {
		setBit(b.nullBitmap.Bytes(), b.length)
	} else {
		b.nullN++
	}
	b.length++
}

// AppendValues will append the values in the v slice. The valid slice determines which values
// in v are valid (not null). The valid slice must either be empty or be equal in length to v. If empty,
// all values in v are appended and considered valid.
func (b *Int64ArrayBuilder) AppendValues(v []int64, valid []bool) {
	if len(v) != len(valid) && len(valid) != 0 {
		panic("len(v) != len(valid) && len(valid) != 0")
	}

	b.Reserve(len(v))
	if len(v) > 0 {
		Int64Traits{}.Copy(b.rawData[b.length:], v)
	}
	b.arrayBuilder.unsafeAppendBoolsToBitmap(valid, len(v))
}

//endregion

func (b *Int64ArrayBuilder) Init(capacity int) {
	b.arrayBuilder.init(capacity)

	b.data = memory.NewPoolBuffer(b.pool)
	bytesN := Int64Traits{}.BytesRequired(capacity)
	b.data.Resize(bytesN)
	b.rawData = Int64Traits{}.CastFromBytes(b.data.Bytes())
}

// Reserve ensures there is enough space for adding the specified number of elements
// by checking the capacity and calling Resize if necessary.
func (b *Int64ArrayBuilder) Reserve(elements int) {
	b.arrayBuilder.reserve(elements, b.Resize)
}

func (b *Int64ArrayBuilder) Resize(capacity int) {
	if capacity < minBuilderCapacity {
		capacity = minBuilderCapacity
	}

	if b.capacity == 0 {
		b.Init(capacity)
	} else {
		b.arrayBuilder.resize(capacity, b.Init)
		b.data.Resize(Int64Traits{}.BytesRequired(capacity))
		b.rawData = Int64Traits{}.CastFromBytes(b.data.Bytes())
	}
}

func (b *Int64ArrayBuilder) Finish() *Int64Array {
	data := b.finishInternal()
	return NewInt64Array(data)
}

func (b *Int64ArrayBuilder) finishInternal() *ArrayData {
	bytesRequired := Int64Traits{}.BytesRequired(b.length)
	if bytesRequired > 0 && bytesRequired < b.data.Len() {
		// trim buffers
		b.data.Resize(bytesRequired)
	}
	res := NewArrayData(PrimitiveTypes.Int64, b.length, []*memory.Buffer{&b.nullBitmap.Buffer, &b.data.Buffer}, b.nullN)
	b.reset()

	return res
}

type Uint64ArrayBuilder struct {
	arrayBuilder

	data    *memory.PoolBuffer
	rawData []uint64
}

func NewUint64ArrayBuilder(pool memory.Allocator) *Uint64ArrayBuilder {
	return &Uint64ArrayBuilder{arrayBuilder: arrayBuilder{pool: pool}}
}

//region: append

func (b *Uint64ArrayBuilder) Append(v uint64) {
	b.Reserve(1)
	b.UnsafeAppend(v)
}

func (b *Uint64ArrayBuilder) AppendNull() {
	b.Reserve(1)
	b.UnsafeAppendBoolToBitmap(false)
}

func (b *Uint64ArrayBuilder) UnsafeAppend(v uint64) {
	setBit(b.nullBitmap.Bytes(), b.length)
	b.rawData[b.length] = v
	b.length++
}

func (b *Uint64ArrayBuilder) UnsafeAppendBoolToBitmap(isValid bool) {
	if isValid {
		setBit(b.nullBitmap.Bytes(), b.length)
	} else {
		b.nullN++
	}
	b.length++
}

// AppendValues will append the values in the v slice. The valid slice determines which values
// in v are valid (not null). The valid slice must either be empty or be equal in length to v. If empty,
// all values in v are appended and considered valid.
func (b *Uint64ArrayBuilder) AppendValues(v []uint64, valid []bool) {
	if len(v) != len(valid) && len(valid) != 0 {
		panic("len(v) != len(valid) && len(valid) != 0")
	}

	b.Reserve(len(v))
	if len(v) > 0 {
		Uint64Traits{}.Copy(b.rawData[b.length:], v)
	}
	b.arrayBuilder.unsafeAppendBoolsToBitmap(valid, len(v))
}

//endregion

func (b *Uint64ArrayBuilder) Init(capacity int) {
	b.arrayBuilder.init(capacity)

	b.data = memory.NewPoolBuffer(b.pool)
	bytesN := Uint64Traits{}.BytesRequired(capacity)
	b.data.Resize(bytesN)
	b.rawData = Uint64Traits{}.CastFromBytes(b.data.Bytes())
}

// Reserve ensures there is enough space for adding the specified number of elements
// by checking the capacity and calling Resize if necessary.
func (b *Uint64ArrayBuilder) Reserve(elements int) {
	b.arrayBuilder.reserve(elements, b.Resize)
}

func (b *Uint64ArrayBuilder) Resize(capacity int) {
	if capacity < minBuilderCapacity {
		capacity = minBuilderCapacity
	}

	if b.capacity == 0 {
		b.Init(capacity)
	} else {
		b.arrayBuilder.resize(capacity, b.Init)
		b.data.Resize(Uint64Traits{}.BytesRequired(capacity))
		b.rawData = Uint64Traits{}.CastFromBytes(b.data.Bytes())
	}
}

func (b *Uint64ArrayBuilder) Finish() *Uint64Array {
	data := b.finishInternal()
	return NewUint64Array(data)
}

func (b *Uint64ArrayBuilder) finishInternal() *ArrayData {
	bytesRequired := Uint64Traits{}.BytesRequired(b.length)
	if bytesRequired > 0 && bytesRequired < b.data.Len() {
		// trim buffers
		b.data.Resize(bytesRequired)
	}
	res := NewArrayData(PrimitiveTypes.Uint64, b.length, []*memory.Buffer{&b.nullBitmap.Buffer, &b.data.Buffer}, b.nullN)
	b.reset()

	return res
}

type Float64ArrayBuilder struct {
	arrayBuilder

	data    *memory.PoolBuffer
	rawData []float64
}

func NewFloat64ArrayBuilder(pool memory.Allocator) *Float64ArrayBuilder {
	return &Float64ArrayBuilder{arrayBuilder: arrayBuilder{pool: pool}}
}

//region: append

func (b *Float64ArrayBuilder) Append(v float64) {
	b.Reserve(1)
	b.UnsafeAppend(v)
}

func (b *Float64ArrayBuilder) AppendNull() {
	b.Reserve(1)
	b.UnsafeAppendBoolToBitmap(false)
}

func (b *Float64ArrayBuilder) UnsafeAppend(v float64) {
	setBit(b.nullBitmap.Bytes(), b.length)
	b.rawData[b.length] = v
	b.length++
}

func (b *Float64ArrayBuilder) UnsafeAppendBoolToBitmap(isValid bool) {
	if isValid {
		setBit(b.nullBitmap.Bytes(), b.length)
	} else {
		b.nullN++
	}
	b.length++
}

// AppendValues will append the values in the v slice. The valid slice determines which values
// in v are valid (not null). The valid slice must either be empty or be equal in length to v. If empty,
// all values in v are appended and considered valid.
func (b *Float64ArrayBuilder) AppendValues(v []float64, valid []bool) {
	if len(v) != len(valid) && len(valid) != 0 {
		panic("len(v) != len(valid) && len(valid) != 0")
	}

	b.Reserve(len(v))
	if len(v) > 0 {
		Float64Traits{}.Copy(b.rawData[b.length:], v)
	}
	b.arrayBuilder.unsafeAppendBoolsToBitmap(valid, len(v))
}

//endregion

func (b *Float64ArrayBuilder) Init(capacity int) {
	b.arrayBuilder.init(capacity)

	b.data = memory.NewPoolBuffer(b.pool)
	bytesN := Float64Traits{}.BytesRequired(capacity)
	b.data.Resize(bytesN)
	b.rawData = Float64Traits{}.CastFromBytes(b.data.Bytes())
}

// Reserve ensures there is enough space for adding the specified number of elements
// by checking the capacity and calling Resize if necessary.
func (b *Float64ArrayBuilder) Reserve(elements int) {
	b.arrayBuilder.reserve(elements, b.Resize)
}

func (b *Float64ArrayBuilder) Resize(capacity int) {
	if capacity < minBuilderCapacity {
		capacity = minBuilderCapacity
	}

	if b.capacity == 0 {
		b.Init(capacity)
	} else {
		b.arrayBuilder.resize(capacity, b.Init)
		b.data.Resize(Float64Traits{}.BytesRequired(capacity))
		b.rawData = Float64Traits{}.CastFromBytes(b.data.Bytes())
	}
}

func (b *Float64ArrayBuilder) Finish() *Float64Array {
	data := b.finishInternal()
	return NewFloat64Array(data)
}

func (b *Float64ArrayBuilder) finishInternal() *ArrayData {
	bytesRequired := Float64Traits{}.BytesRequired(b.length)
	if bytesRequired > 0 && bytesRequired < b.data.Len() {
		// trim buffers
		b.data.Resize(bytesRequired)
	}
	res := NewArrayData(PrimitiveTypes.Float64, b.length, []*memory.Buffer{&b.nullBitmap.Buffer, &b.data.Buffer}, b.nullN)
	b.reset()

	return res
}
