// Code generated by type.go.tmpl.
// DO NOT EDIT.

package math

// <no value>

import (
	"github.com/influxdata/arrow/array"
)

type Float64Funcs struct {
	sum func(a *array.Float64) float64
}

var (
	Float64 Float64Funcs
)

func initFloat64AVX2() {
	Float64.sum = sum_float64_avx2
}

func initFloat64SSE4() {
	Float64.sum = sum_float64_sse4
}

func initFloat64Go() {
	Float64.sum = sum_float64_go
}

// Sum returns the summation of all elements in a.
func (f Float64Funcs) Sum(a *array.Float64) float64 {
	return f.sum(a)
}

func sum_float64_go(a *array.Float64) float64 {
	acc := float64(0)
	for _, v := range a.Float64Values() {
		acc += v
	}
	return acc
}
