// Code generated by type.go.tmpl.
// DO NOT EDIT.

package math

// <no value>

import (
	"github.com/influxdata/arrow/array"
)

type Uint64Funcs struct {
	sum func(a *array.Uint64) uint64
}

var (
	Uint64 Uint64Funcs
)

func initUint64AVX2() {
	Uint64.sum = sum_uint64_avx2
}

func initUint64SSE4() {
	Uint64.sum = sum_uint64_sse4
}

func initUint64Go() {
	Uint64.sum = sum_uint64_go
}

// Sum returns the summation of all elements in a.
func (f Uint64Funcs) Sum(a *array.Uint64) uint64 {
	return f.sum(a)
}

func sum_uint64_go(a *array.Uint64) uint64 {
	acc := uint64(0)
	for _, v := range a.Uint64Values() {
		acc += v
	}
	return acc
}
